### ISSUE TITLE
Visualize the predicted gaze in the video clip

### ISSUE THREAD

**Issue by yuhufeng** [BolinLai/GLC#2]
Hello, this article I think is very novel to introduce the Global-Local Correlation. But when I wanted to integrate it into my own work, I encountered the problem of finding the result of the estimated gaze data and visualizing it. Is there a function for the qualitative evaluation to visualize the predicted gaze? Thank you very much!

**Comment by BolinLai** [comment]
The output of the model is a heatmap. You can resize it to match the size of input and overlay it on the input image.
