### ISSUE TITLE
Inference on custom video

### ISSUE THREAD

**Issue by Mikes95** [BolinLai/GLC#3]
Hello. Thanks for the code. I need to run inference on some custom videos. I also saw a previous issue related. I was wondering what script I have to use. I tested train_net.py with this configuration:
python tools/run_net.py \
 --cfg configs/Egtea/MVIT_B_16x4_CONV.yaml \
 TRAIN.ENABLE False \
 TEST.BATCH_SIZE 32 \
 NUM_GPUS 1 \
 OUTPUT_DIR checkpoints/GLC \
 TEST.CHECKPOINT_FILE_PATH /Weights/MViT_Egtea_ckpt.pyth \
 DATA.PATH_PREFIX <what to put here? a path to a csv? organized how? just with video path?>

I have tried with:
python tools/run_net.py \
 --cfg configs/Egtea/MVIT_B_16x4_CONV.yaml \
 TRAIN.ENABLE False \
 TEST.BATCH_SIZE 32 \
 NUM_GPUS 1 \
 OUTPUT_DIR checkpoints/GLC \
 TEST.CHECKPOINT_FILE_PATH /Weights/MViT_Egtea_ckpt.pyth \
 DATA.PATH_PREFIX /data/my_test.csv

my_test.csv contains just a row with the .mp4 file path
/EGTEA_Gaze+/Trimmed_Action_Clips/cropped_clips/OP01-R01-PastaSalad/OP01-R01-PastaSalad-66680-68130-F001597-F001639.mp4

But when I execute I receive this error:
NotADirectoryError: [Errno 20] Not a directory: 'Path/GLC/GLC/data/my_test.csv/gaze_data/OP01-R06-GreekSalad.txt'

**Comment by BolinLai** [comment]
Hi, if you want to do inference using EGTEA checkpoint, the code will read this file `data/test_gaze_official.csv` for video paths by default. You can find the code in line 86 [here](https://github.com/BolinLai/GLC/blob/main/slowfast/datasets/egtea_gaze.py). You can update it to your video path. If you use the full path, just set DATA.PATH_PREFIX as an empty string.

**Comment by Mikes95** [comment]
I've successfully executed the script, but I have a question regarding the model's output. The tensor 'preds' has the shape torch.Size([1, <batch_size>, 8, 64, 64]). I'm curious about the significance of the number 8 in this context. Are there any built-in functions or scripts available to generate heatmaps from this output, or would I need to create my own solution?

**Comment by BolinLai** [comment]
Gald to know you successfully ran it. The model downsamples the video in time by uniformly sampling 8 frames in the first 64 frames and then predicts the gaze on the 8 frames at the same time. Specifically, assuming the indices of the 64 frames are [0, 1, 2, ..., 63]. The model takes 8 frames at [0, 9, 18, 27, 36, 45, 54, 63]. The gaze doesn't shift much between two neighboring frames, so we sample frames by a fixed stride to cover longer footage. You can get the gaze location in between by interpolation. If you want to do inference on a long video, a sliding window strategy is needed.
