### ISSUE TITLE
About your new work (Listen to Look into the Future: Audio-Visual Egocentric Gaze Anticipation)

### ISSUE THREAD

**Issue by TheMVPotato** [BolinLai/GLC#5]
Thank you for sharing excellent works!

I've noticed your recent work(Listen to Look into the Future: Audio-Visual Egocentric Gaze Anticipation), and I'm very interested in it. Sorry to contact you here，as the current work has not yet been open-sourced.

While attempting to replicate the results, I found that there's no audio data available for videos as "0d271871-c8ba-4249-9434-d39ce0060e58" and "7d8b9b9f-7781-4357-a695-c88f7c7f7591" in the dataset Ego4D. 

After double-checking, I've confirmed that the original video data indeed lacks audio. I'm wondering if there are correct videos with audio included. If so, could you kindly provide a sample of the correct video? If not, could you please explain how you partitioned the dataset?

**Comment by TheMVPotato** [comment]
> Sorry for the late response. I will release the audio stream of the two videos later.

Thank you very much for your response. I'm sincerely grateful for your commitment to releasing the corrected dataset.

If possible, please do let me know once you've published the corrected videos. It would be immensely helpful for my work.

Given the tight deadline for my paper, I would greatly appreciate it if you could expedite the release of the correct videos. This will enable me to redo the relevant experiments and ensure the smooth progress of my research.

If possible, could you also share with me the partitioning details for your Aria dataset? I'm interested in conducting related experimental research as well. 

Once again, thank you for your understanding and support. Looking forward to hearing from you soon.

**Comment by wyf105360092** [comment]
> Sorry for the late response. I will release the audio stream of the two videos later.

Hi, I've encountered the same issue. Has the correct video containing the audio stream been released?

**Comment by BolinLai** [comment]
I uploaded two missing audio streams via this link: https://drive.google.com/drive/folders/1iZuuRiflog9AazCtLXa9PbIYg-S3vENs?usp=drive_link
