### ISSUE TITLE
Can not reproduce the results

### ISSUE THREAD

**Issue by Xiong-Huiyu** [BolinLai/GLC#8]
Thanks for your excellent work! After I trained on the code from your github, the results I got were somewhat different from the paper. 

After training exclusively with the weights you posted, I get the results on egtea gaze+:

{"f1": 0.43194, "precision": 0.34518, "recall": 0.57696}

However, the results shown in your paper are:

{"f1": 0.448, "precision": 0.353, "recall": 0.612}

And on ego4d, I get:

{"f1": 0.40477, "precision": 0.31544, "recall": 0.56468}

However, the results shown in your paper are:

{"f1": 0.431, "precision": 0.347, "recall": 0.585}

Both of them are lower than yours. I don't know what's going on, can you help me find a solution together?

About the environment, I use CUDA Version: 12.2 and 2 NVIDIA A800 80GB PCIe.

The running script is:

on egtea gaze+：
CUDA_VISIBLE_DEVICES=0,1, python tools/run_net.py --init_method tcp://localhost:9877 --cfg configs/Egtea/MVIT_B_16x4_CONV.yaml TRAIN.BATCH_SIZE 16 TEST.BATCH_SIZE 128 NUM_GPUS 2 TRAIN.CHECKPOINT_FILE_PATH /data1/xhy/ego/GLC-main/pretrain/K400_MVIT_B_16x4_CONV.pyth OUTPUT_DIR checkpoints/GLC_egtea DATA.PATH_PREFIX /data1/xhy/ego/datasets/egtea

on ego4d：
CUDA_VISIBLE_DEVICES=0,1, python tools/run_net.py --init_method tcp://localhost:9877 --cfg configs/Ego4d/MVIT_B_16x4_CONV.yaml TRAIN.BATCH_SIZE 16 TEST.BATCH_SIZE 128 NUM_GPUS 2 TRAIN.CHECKPOINT_FILE_PATH /data1/xhy/ego/GLC-main/pretrain/K400_MVIT_B_16x4_CONV.pyth OUTPUT_DIR checkpoints/GLC_ego4d DATA.PATH_PREFIX /data1/xhy/Ego4D_gaze/clips.gaze

The hyperparameter setting is:

on egtea gaze+：
TRAIN:
  ENABLE: True
  DATASET: egteagaze
  BATCH_SIZE: 12
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_EPOCH_RESET: True
DATA:
   PATH_PREFIX: '/data1/xhy/ego/datasets/egtea'
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 256
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  TARGET_FPS: 24
  USE_OFFSET_SAMPLING: False
  GAUSSIAN_KERNEL: 19
MVIT:
  ZERO_DECAY_POS_CLS: False
  SEP_POS_EMBED: True
  DEPTH: 16
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.2
  NORM: "layernorm"
  MODE: "conv"
  CLS_EMBED_ON: False
  GLOBAL_EMBED_ON: True
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[1, 1, 2, 2], [3, 1, 2, 2], [14, 1, 2, 2]]
  DROPOUT_RATE: 0.0
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  ZERO_WD_1D_PARAM: True
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.0001 # 0.0001
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 5.0
  LR_POLICY: cosine
  MAX_EPOCH: 25
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
MODEL:
  NUM_CLASSES: 400
  ARCH: mvit
  MODEL_NAME: GLC_Gaze
  LOSS_FUNC: kldiv
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: egteagaze
  BATCH_SIZE: 12
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 1
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True

NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .

on ego4d：
TRAIN:
  ENABLE: True
  DATASET: ego4dgaze
  BATCH_SIZE: 12
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_EPOCH_RESET: True
DATA:
  PATH_PREFIX: '/data1/xhy/Ego4D_gaze/clips.gaze'
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 256
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  TARGET_FPS: 30
  USE_OFFSET_SAMPLING: False
  GAUSSIAN_KERNEL: 19
MVIT:
  ZERO_DECAY_POS_CLS: False
  SEP_POS_EMBED: True
  DEPTH: 16
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.2
  NORM: "layernorm"
  MODE: "conv"
  CLS_EMBED_ON: False
  GLOBAL_EMBED_ON: True
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[1, 1, 2, 2], [3, 1, 2, 2], [14, 1, 2, 2]]
  DROPOUT_RATE: 0.0
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  ZERO_WD_1D_PARAM: True
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.0001
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 5.0
  LR_POLICY: cosine
  MAX_EPOCH: 15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05 
  OPTIMIZING_METHOD: adamw
MODEL:
  NUM_CLASSES: 400
  ARCH: mvit
  MODEL_NAME: GLC_Gaze
  LOSS_FUNC: kldiv
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: ego4dgaze
  BATCH_SIZE: 12
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 1
DATA_LOADER:
  NUM_WORKERS: 8 
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True

NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .

What can I do to reproduce the results of your experiments?
Looking forward to your reply!

**Comment by BolinLai** [comment]
As I said, you need to run the evaluation code using the released weights to make sure there's no mistake in the env and dataset. If you get the same number, we can move forward.

**Comment by Xiong-Huiyu** [comment]
The evaluation code shows:
egtea gaze+: {"f1": 0.44778, "precision": 0.35292, "recall": 0.61236}
ego4d: {"f1": 0.43126, "precision": 0.34701, "recall": 0.56953}
It is the same as what you list on the paper.

**Comment by BolinLai** [comment]
Cool. Then can you let me know if you are using the hyperparameters I released with the code, and which checkpoint you evaluated? The code may automatically test the last checkpoint but usually this is not the best one.
